#!/bin/sh
#
# To enable this hook, rename this file to "post-merge".
#

echo "============= P4 Submit ============="

changed_files=(`git diff-tree -r --name-status ORIG_HEAD HEAD`)

files_add=""
files_del=""
files_mod=""

p4_initialize() {
    # TODO
    echo "p4 set P4USER=$1"
    echo "p4 set P4PASSWD=$2"
    echo "p4 set P4CLIENT=$3"
}

p4_revert_unchanged() {
    p4 revert -a
#    echo "p4 revert -a"
}

p4_add() {
    p4 add $1
#    echo "p4 add $1"
}

p4_delete() {
    p4 delete $1
#    echo "p4 delete $1"
}

p4_modify() {
    p4 edit $1
#    echo "p4 edit $1"
}

p4_submit() {
    p4 submit
#    echo "p4 submit"
}

collect_files() {
    local action=0
    for tag in ${changed_files[@]}
    do
        case ${tag} in
            M) action=1;; # Modify
            A) action=2;; # Add
            D) action=3;; # Delete
            *)
                case ${action} in
                    1) files_mod+="${tag} ";; # Modify
                    2) files_add+="${tag} ";; # Add
                    3) files_del+="${tag} ";; # Delete
                    *) echo "No action for : ${tag}";; # Unknow
                esac
                ;;
        esac
    done
}

# First delete, then add. It is for rename action.
p4_open_files() {
    if [ "${files_del}" != "" ]; then
        p4_delete "${files_del}"
    fi

    if [ "${files_add}" != "" ]; then
        p4_add "${files_add}"
    fi

    if [ "${files_mod}" != "" ]; then
        p4_modify "${files_mod}"
    fi

    # show opened files
#    echo "========= opened files =========="
#    p4 opened
#    echo "================================="
}

_main() {
    # Todo for user login etc..
    p4_initialize "UserName" "Password" "CLIENT"

    collect_files

    p4_open_files
    p4_revert_unchanged
    p4_submit
}

_main

